### ISSUE TITLE
QRCode is not defined

### ISSUE THREAD

**Issue by Hu4F00d** [Thanix/ember-qrcode#1]
I'm getting `Uncaught ReferenceError: QRCode is not defined` when trying to use the {{qr-code}} component. I checked the plugin component and the line:  `var qr = new QRCode(0, 1);` says that QRCode is undefined.

**Comment by OrKoN** [comment]
Probably, it needs this as a dependency https://davidshimjs.github.io/qrcodejs/

**Comment by itsadrake** [comment]
Thanks for bringing this to my attention. I forgot to load the JS dependency. It should be fixed now.
